# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AlanPortfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://gengoffeewebsite.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bfd78841932e4abf82d6369f885b175d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1b22cf5a292a49ca9a485c8f7c3f3c51 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: gengoffeewebsite.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfd78841932e4abf82d6369f885b175d }}/alan-portfolio:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AlanPortfolio'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_676e05dcdb51461ab67e29194d7fb291 }}
        images: 'gengoffeewebsite.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfd78841932e4abf82d6369f885b175d }}/alan-portfolio:${{ github.sha }}'